bpftrace: Autospec creation for update from version 0.19.1 to version 0.20.3
Aboorva Devarajan (2):
      tools/runqlen.bt: remove 'runnable_weight' field
      tools/mdflush.bt: update include headers for non-BTF builds

Adam Jensen (2):
      Sync resolve_* declaration types with their implementations
      Fix (arm32): Sync offset vector type with the one used by libbpf

Alastair Robertson (9):
      Fix Invalid Strict Weak Ordering Predicate
      Runtime tests: Fix a crash in the test framework
      BTF: Handle array types
      CI: Run clang-format on all branches
      CMake: Don't trigger full rebuild when a test file changes
      CMake: Fix testlib dependencies
      CMake: Clean up testprog rules
      Runtime tests: Adjust meaning of BPFTRACE_RUNTIME_TEST_EXECUTABLE env var
      Add missing header to fix Fedora build

Alison Chaiken (1):
      docs: guard kernel headers includes in example (#2919)

Basil Crow (1):
      Add PPID field to `execsnoop.bt`

Costa Shulyupin (5):
      execsnoop: use `strftime` instead of `elapsed`
      threadsnoop: use `strftime` instead of `elapsed`
      threadsnoop: increase PID field width and align to the right
      fix PR number in CHANGELOG
      improve killsnoop output

Daniel Xu (47):
      apparser: kfunc: Report better errors for missing comma
      apparser: Provide better error messages for bad argument counts
      Update CHANGELOG
      Reduce visual noise in issue templates
      codegen: Fix algorithm comment in createLog2Function()
      hist: Support values creater than 4G
      Update CHANGELOG
      nix: Update libbpf
      utils: Fix TOCTOU in get_pid_exe()
      embedded: Delete embedded build infrastructure
      embedded: Delete CMake support for embedded builds
      build: ci: Remove usage of -DUSE_SYSTEM_BPF_BCC flag
      docs: Remove references to embedded builds
      docs: Consolidate build instructions in developers.md
      ci: Replace embedded quay.io image with appimage
      Update CHANGELOG
      build: Fix up llvm 16 static build
      ci: Add static build job
      ci: Name appimage artifact 'bpftrace'
      docs: Document appimage download locations
      snap: Delete support
      Update CHANGELOG
      scripts: Support custom OUT dir for create-assets.sh
      ci: Build and upload release artifacts on release
      Move top-level resources/ into src/resources/
      ci: Install optional runtime test deps
      tests: Fix EXPECT_JSON error message
      tests: json: Use EXPECT_JSON directive
      docker: Add minimal Dockerfiles for major distros
      ci: Add GHA job to build against different distros
      docs: Update INSTALL.md to point to docker documentation
      Update CHANGELOG
      ci: Add llvm17 job
      Fix nix-flake-check warning
      hist: PR followups
      Remove extraneous comment
      NFC: Extract std::filesystem detection to header
      Add find_in_path() helper
      Add generate_section() to generate contents of .BTAOT section
      Implement build_binary() to build final AOT binary
      Wire up section injection logic inside generate()
      utils: Remove unused config.h include
      docs: cn: jp: Guard kernel headers includes in example (#2924)
      ci: Set continue-on-error for matrix jobs
      v0.20.1 release
      v0.20.2 release
      v0.20.3 release

Delyan Kratunov (5):
      Introduce BpfProgram to track bytecode relationships
      Inline map relocations into BpfProgram
      Emit basic debug info for function definitions
      Implement relocations against .text for subprogs
      Implement .BTF.ext func_info relocation

Gaurav Kamathe (5):
      Fixing shebang in ssllatency.bt and sslsnoop.bt
      docs: fixed broken symlink to bpftrace man page
      Fixing some minor typos at multiple places
      Fixing some more minor typos
      Fixing execsnoop.bt failure due to PPID addition

Ivan Kelly (1):
      Allow uprobes to work across filesystem namespace boundaries

Jay Kamat (1):
      Add currently known plugins to README

Jean-Baptiste Denis (1):
      Correct minor typo in bpftrace.adoc

Jesus Sanchez-Palencia (1):
      Fix symbolication on 32-bit userspace / 64-bit kernel

Jiri Olsa (7):
      Detect libbpf uprobe_multi api is present
      Add feature check for uprobe_multi
      Add support to attach uprobe_multi
      Add --no-feature option
      Add runtime tests for uprobe_multi link
      Update CHANGELOG
      Update libbpf submodule

Jon Haslam (1):
      remove fd leaks in AttachedProbe::load_prog()

Jordan Rome (28):
      Add pid and host targeting for uprobes/uretprobes (#2757)
      Add 'NEW_PIDNS' directive to runtime tests
      Increment deref'ed pointer for count builtin
      Add codegen-tests.sh to update or run the tests
      Increment deref'ed pointer for sum builtin
      [CreateMapElemAdd] add missing CreateLifetimeEnds
      [min] update value directly in memory if available
      [max] update value directly in memory if available
      [avg/stats] update value directly in memory if available
      [hist] update value directly in memory if available
      [lhist] update value directly in memory if available
      Fix documentation of Environment variables
      Add fentry/fexit aliases for kfunc/kretfunc
      [uprobe] support for pid targeting for shared libs
      Fix uprobe multi probe with target wildcard
      Fix bpftrace -l when kfunc is not available
      Fix memory leak when listing probes
      [kfunc/kretfunc] fix arg and retval resolution
      [usdt][runtime test] add separate systemtap check
      Add Config class
      Fix: strerror string not quoted
      Add 'get_helper_error_msg' utility
      [output] Use a switch for 'is_quoted_type'
      Add new 'config' syntax
      Standardize config and env var names
      Remove env-only configs from config class
      Fix runtime tests target name in readme
      Fix security hole checking unpacked kernel headers (#3033)

Khem Raj (1):
      Adjust to build with llvm 17

Luigi Rizzo (2):
      TEST: implement EXPECT_FILE and EXPECT_JSON
      hist: log2 histograms with finer granularity

Manu Bretelle (1):
      elf_parser: Fix invalid-null-argument

Mathias Nyman (1):
      Fix incorrect variable name in the documentation

Pitt (1):
      Update reference_guide.md - struct navigation '->' (#2843)

Rong Tao (1):
      utils: Fix error: ‘PATH_MAX’ was not declared in this scope

Shane Xie (1):
      Add the GetScratchMap and DebugOutput utilities (#2746)

Shung-Hsi Yu (2):
      Removed unused ptr_to_u64() function
      Fix build issue with UAPI header of older kernel

Sim Sun (1):
      utils: use /data/local/tmp as temprary dir on Android (#2828)

Tianchen Ding (1):
      tests: runtime: fix kprobe_offset_module* on aarch64

Tomislav Novak (1):
      Assorted clang warning fixes

Viktor Malik (20):
      Fix JSON output for cgroup_path
      Runtime tests: mark timed-out tests in overview
      Runtime tests: prettify total elapsed time
      Parse available_filter_functions lazily
      Pass BTF info on program load
      Add new builtin to get the number of map elements
      Runtime tests runner: do not fail on JSON parsing
      Fix uprobe name for uprobe_multi + wildcard target
      Unit tests: add separate tests for kprobe_multi
      Unit tests: add separate tests for uprobe_multi
      Fix attachment/listing of wildcarded module kfuncs
      Use unique names for stackid maps
      Config: get stack mode name->enum map dynamically
      Introduce BpfBytecode class
      Introduce unit tests for the new BpfBytecode class
      Probe matcher: improve matching kprobes
      Probe matcher: improve matching kfuncs without BTF
      Fixup generated BTF for older kernels
      Docker: drop unneeded packages from Fedora build
      v0.20.0 release

Zigit Zo (2):
      Add jiffies builtin with bpf_jiffies64
      Correct some printf types in runtimes tests

gkamathe (1):
      Update tools/execsnoop.bt

havefuncoding1 (1):
      Fixe cmake download path which had arch hardcoded to x86_64 (#2824)

云微 (1):
      docs cn: fix broken man link